### ISSUE TITLE
Awesome website, 2 quick questions

### ISSUE THREAD

**Issue by npoggenburg** [hexagoncircle/ryan-mulligan-dev#16]
Hi,

nice clean website. I am learning from your website right now and found 3 things, i cant explain to myself:

1.  Is there a reason why you A. name the file sizes instead of size? Analog to color(s).css or font(s).css? https://github.com/hexagoncircle/ryan-mulligan-dev/blob/c1ff1d924ffe02d20e1768599834cbdc33a3b9a5/src/css/_sizes.css
2. Is there a reason you use html instead of :root only in this file? https://github.com/hexagoncircle/ryan-mulligan-dev/blob/c1ff1d924ffe02d20e1768599834cbdc33a3b9a5/src/css/_sizes.css#L3
3. After a little digging i found out, you are creating custom rules for apply and mixin in your lightningcss configuration. As far as i can see, this is only used to setup the colors. Is there a deeper reason to go off css basic functionality for only this feature and would it not be easier to just use the scss preprocessor to handle this task?

I am not sure if its appreciated to point at things, but i really like to question even little things we do in our daily work. Keep up inspiring people!

Best regards,
Nico

**Comment by hexagoncircle** [comment]
Appreciate the questions, @npoggenburg! 🙌 

1. No reason, I honestly didn't notice that.
2. Same answer as above. I'll be refactoring and tidying up over time.
3. Sass is still excellent and recommended. My preference (at the moment) is Lightning CSS. Having a `mixin` is useful when faced with ruleset repetition which, as far as I can tell, is unavoidable in native CSS where color values can either be set based on a user's system settings or by a user explicitly selecting a light/dark appearance.
